### ISSUE TITLE
downloading gifs to script.module.metadatautils

### ISSUE THREAD

**Issue by mikemorkodi** [kodi-community-addons/script.module.metadatautils#22]
hi ,
it keeps downloading gifs to the folder .kodi\userdata\addon_data\script.module.metadatautils\  even though i disabled gifs downloading in my skin (EMINENCE 2 MOD (REVIVED)) , the thing is that this folder getting "heavy" because some gifs are even 10 MB....
thanks..

**Comment by Angelinas1** [comment]
site for this is down...http://www.consiliumb.com/
