### ISSUE TITLE
Where to best put personal keys

### ISSUE THREAD

**Issue by hablaras** [kodi-community-addons/script.module.metadatautils#29]
Hi Marcel,

Up until now I just put my personal keys in the .py modules, but you state you can also put them in the settings.xml:

https://github.com/marcelveldt/script.module.metadatautils

**1. User/Personal api keys. A user can set his own, personal api key in the Kodi addon settings for the module.**

The settings.xml file does not exist in 

`osmc\.kodi\userdata\addon_data\script.module.metadatautils\`

so I've created one manually with this content:

```
<settings>
     <setting id="fanarttv_apikey" value="keyvaluehere"/>
     <setting id="omdbapi_apikey" value="keyvaluehere"/>
     <setting id="tmdb_apikey" value="keyvaluehere"/>       
</settings>
```

but that doesn't seem to work.

What is the best way to configure the keys?

Greetings,

Hablaras

**Comment by marcelveldt** [comment]
Just open the addon settings in Kodi dor the metadata module. Once you do that, the settings file will be created automatically.

**Comment by hablaras** [comment]
I was never able to find the entry for "Metadata & Artwork module". I just saw it in the addons folder and kodi logs, that's why in the past I created the settings.xml in the "userdata/addon_data/script.module.metadatautils" folder.

That got me thinking and I just downloaded it again from github and installed it; overwriting the addon I already had.

Under menu "Add-ons" it is now **only** under "recently updated", but not in any of the categories of "my addons". And not findable using "search" with e.g. the keyword "meta". So, when it is not a recently updated addon anymore, I would not be able to configure it.

I see there that the type is "addon libraries". What category under "my addons" should it be in?

(I assume these addon categories are fixed and that it is not possibly filtered by the skin I am using. 
I am using OSMC / Kodi 17.6, Eminence 2 MOD skin.)

**Comment by pdf** [comment]
@marcelveldt I don't think settings are available for more recent versions of Kodi since they categorised the addons, as there's no category displayed for `xbmc.python.module`-only addons.  Might need to add a dummy `xbmc.python.script` or similar to make it show up under program addons, and allow the settings to be modified.

**Comment by randellhodges** [comment]
I know I'm a year behind, but I came across the same question. I think the reason it wasn't loading is that without a version in the settings tag, Kodi goes down a different path to load/parse the xml.

With `<settings version="2">` it seems to work.

**Comment by hablaras** [comment]
Hey Randell,

Thanks! I am still using this setup so I'll try your suggestion!

Greetings,

Hablaras

**Comment by raven428** [comment]
```kodi-send --action="Addon.OpenSettings(script.module.metadatautils)"``` - next year, next answer, @hablaras.

**Comment by hablaras** [comment]
@raven428 Nice! That works as well. 
I had already solved it with the **version="2"** tip, but this is a handy alternative.
