### ISSUE TITLE
Fanart.tv problems

### ISSUE THREAD

**Issue by andrea75** [kodi-community-addons/script.module.metadatautils#31]
In this days there a lot of problems with Fanart.tv scrapers, due site problems. The result is a lot of missing images. This is what I receive on the LOG:
https://paste.kodi.tv/izeqinifox.kodi

So, it's possibile to completely disable scrapers on PVR from Fanart.tv, and leave only TVDB and TMDB? I tray to remove Fanart.tv API key from settings, but it doesn't work.

**Comment by Angelinas1** [comment]
Fanart.tv site problem was fixed...now is ok for PVR....
