### ISSUE TITLE
 Script.Module.Metadatautils incompatibility with Kodi Leia/18

### ISSUE THREAD

**Issue by oattes** [kodi-community-addons/script.module.metadatautils#36]
I figured it was finally time to migrate from Krypton to Leia but Titan was a base requirement for me. Unfortunately none of the current mods seemed to have fixed a problem with 'Skin Helper Widgets' for Music. Many of them don't work -- for me it was a desire for the 'Random Albums' widget that drove me to finally investigate.

The fix is pretty simple (for me at least).

Change this line in the script.module.metadatautils\lib\kodi-constants.py from

FIELDS_ALBUMS = ["title", "fanart", "thumbnail", "genre", "displayartist", "artist", "genreid",
    "musicbrainzalbumartistid", "year", "rating", "artistid", "musicbrainzalbumid", "theme", "description",
    "type", "style", "playcount", "albumlabel", "mood", "dateadded"]

to

FIELDS_ALBUMS = ["title", "fanart", "thumbnail", "genre", "displayartist", "artist",
    "musicbrainzalbumartistid", "year", "rating", "artistid", "musicbrainzalbumid", "theme", "description",
    "type", "style", "playcount", "albumlabel", "mood", "dateadded"]

Note: Kodi 18 JSON API no longer supports the parameter "genreid" for the GetAlbums method for the AudioLibrary (class).

I thought that I'd mention this (rudimentary) fix for the mod authors (or any one else interested) who might be able to include it in their repositories. (In retrospect, after I had tracked this down, I see that a user 'Angelinas1' has already noted this fix in github -- that would have saved me some time!)

cheers,
Lee

**Comment by kekukui** [comment]
> **I figured it was finally time to migrate from Krypton to Leia but Titan was a base requirement for me.**

There is a Titan beta for Leia in the official Kodi repo but it does not even install.  Are you saying you got this working?  (I can confirm that Titan Bingie runs on Leia, but it is a bit buggy.)

**Comment by oattes** [comment]
For me, Titan Vanilla did most of the work, but music widgets did not work. I tracked down this bug and fixed the music widgets. I did 'get Titan to work' for me on Leia. However, Titan for me may not be Titan for you -- it's a very complex skin, so your mileage may vary.

**Comment by Angelinas1** [comment]
This isue was fixed 
marcelveldt commented on 7 Jan 2018
https://github.com/kodi-community-addons/script.module.metadatautils/pull/27
