### ISSUE TITLE
this will not install in kodi 19 

### ISSUE THREAD

**Issue by SerpentDrago** [kodi-community-addons/script.module.metadatautils#40]
`>  <import addon="script.module.thetvdb" version="0.0.1" />  `

the updated version has not been added to marcels repo 

and 

`>    <import addon="script.module.beautifulsoup" version="3.0.8" />`

can not be found , obviously bs4 is been updated and added to repo , but not 1 , i dont' know if with the latest fix's its even needed.

Running into dep hell trying to work on porting a skin from kodi 18 to 19 . 

Thanks

**Comment by SerpentDrago** [comment]
and it needs this updated version of musicbrainz
 > 

https://github.com/AnonTester/script.module.musicbrainz

**Comment by Angelinas1** [comment]
Kodi 19 is still in RC...the plan is to publish zip folder for tester, then all module will go on Py3.
Need some time....it takes a little patience

**Comment by SerpentDrago** [comment]
well it just seems most everything has been done and it works in both 18 and 19 , just comment out python import. 

I was almost able to install everything right from repo , except some of the points i made . 

Its ok for now , i got the skin i'm working on to install  , manually installing between your fix's and annons 

thanks for everything . I'll prob for now just throw all the fixed deps i need on the repo with my skin . 

Again thanks for everything . just noticing out the few issues i had

**Comment by Angelinas1** [comment]
Changed all module and script in Py3
Please test, for now need manual before add to repo

**Comment by Converted007** [comment]
> Changed all module and script in Py3
> Please test, for now need manual before add to repo

What about kodi 18.9? Now it gives an error that python 3.0.0 cant be installed with all your addons...

**Comment by SerpentDrago** [comment]
> > Changed all module and script in Py3
> > Please test, for now need manual before add to repo
> 
> What about kodi 18.9? Now it gives an error that python 3.0.0 cant be installed with all your addons...

Well they didn't do a dual repo. It's matrix only now. So you will have to manually install any deps or make your own repo with them

**Comment by Converted007** [comment]
> For Matrix lower disable repository.marcelveldt, when you go to offiicial version just enable repo for auto-update.
> No need to make noise :)

I dont have any marcelveldt repo. Only the venom repo. And even older versions dont install anymore...

**Comment by SerpentDrago** [comment]
> > For Matrix lower disable repository.marcelveldt, when you go to offiicial version just enable repo for auto-update.
> > No need to make noise :)
> 
> I dont have any marcelveldt repo. Only the venom repo. And even older versions dont install anymore...

This is not the place to discus issues with 3rd party addons , grab the deps you need manually and install . 

Please don't mention 3rd party addons , thanks

**Comment by SerpentDrago** [comment]
@Angelinas1 Thanks for updating the repo for matrix ! makes my life easier  !

**Comment by Converted007** [comment]
> @Converted007
> 
> This is not the place to discus issues with 3rd party addons , grab the deps you need manually and install . or ask for help on a forum that deals with stuff like that such as addons4kodi
> 
> Please don't mention 3rd party addons on this github , thanks

Im not talking about any addon. Im talking about a repo. And about the metadatautils not being available anymore for kodi 18.9...

**Comment by Converted007** [comment]
> @Angelinas1 Thanks for updating the repo for matrix ! makes my life easier !

Im not talking about any addon. Im talking about a repo. And about the metadatautils not being available anymore for kodi 18.9...

**Comment by Angelinas1** [comment]
> > For Matrix lower disable repository.marcelveldt, when you go to offiicial version just enable repo for auto-update.
> > No need to make noise :)
> 
> I dont have any marcelveldt repo. Only the v.... repo. And even older versions dont install anymore...
You write that you don't use this repo....How can I help you ?
metadatautils is same for Leia and Matrix
https://github.com/kodi-community-addons/repository.marcelveldt/blob/master/script.module.metadatautils/script.module.metadatautils-1.0.37.zip
