### ISSUE TITLE
TOP250 Work only for some movies

### ISSUE THREAD

**Issue by wsx79** [kodi-community-addons/script.module.metadatautils#42]
I use aura mod skin.
Top 250 not see for all movie but only for some of that.
Other metadata working fine.

**Comment by Angelinas1** [comment]
Top 250 No: will show only for your library movies and tvshow.

**Comment by wsx79** [comment]
> 
> 
> Top 250 No: will show only for your library movies and tvshow.

I give you an Example with photo.
All movies are from my local library
![1](https://user-images.githubusercontent.com/68690475/115139313-8202df00-a031-11eb-8bc6-2dfd79bc3b23.jpg)
![2](https://user-images.githubusercontent.com/68690475/115139316-83340c00-a031-11eb-9860-d19dc0bd1cc4.jpg)
![3](https://user-images.githubusercontent.com/68690475/115139317-84fdcf80-a031-11eb-8422-99b1c462e6b4.jpg)
![4](https://user-images.githubusercontent.com/68690475/115139320-862efc80-a031-11eb-946d-525ceaa0ac0b.jpg)

I some I see TOP 250. In other not.
I don't know if is a Skin problem (but I think not because, in this case, I can't see in any movies) or a metadata error.

**Comment by Angelinas1** [comment]
simplecache missed that info...(sugest to waith 7 days)
@use_cache(7) imdb have limit to prevent overloading the server

Just try 2 movies without imdTop250, and both of them are OK.

![screenshot00002](https://user-images.githubusercontent.com/7657140/115154013-0dec2980-a079-11eb-8e44-e267855b18a6.png)
![screenshot00003](https://user-images.githubusercontent.com/7657140/115154015-10e71a00-a079-11eb-8dfd-f58fe8cd13bb.png)
